"""
ORFS CTS sweep — runs 10 clock_tree_synthesis variants on a placed ODB.

Generates a TCL script per CTS run and calls `openroad -exit` inside the
ORFS Singularity container.  Writes knobs.json + metrics.json to each
CTS-{i} directory so 6-parse-cts-reports-orfs.py can collate them.

Usage (called by main-hpc-orfs.py on the HOST, not inside the container):
  python3 5-run-cts-orfs.py <placement_id> <pdk>

PDK-specific LEF/Liberty paths inside the ORFS container are hardcoded
because the container's PDK files never change.
"""

import json
import os
import random
import shutil
import subprocess
import sys
from pathlib import Path

# ── Env ───────────────────────────────────────────────────────────────────────
CTS_BENCH_ROOT = os.environ.get(
    "CTS_BENCH_ROOT",
    os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")),
)
ORFS_SIF      = os.environ.get("ORFS_SIF",     os.path.join(os.path.expanduser("~"), "singularity", "orfs.sif"))
CONTAINER_CMD = os.environ.get("CONTAINER_CMD", "apptainer" if shutil.which("apptainer") else "singularity")

# ── PDK paths INSIDE the ORFS container ───────────────────────────────────────
ORFS_FLOW    = "/OpenROAD-flow-scripts/flow"
OPENROAD_BIN = "/OpenROAD-flow-scripts/tools/install/OpenROAD/bin/openroad"

PDK_CONTAINER_PATHS = {
    "asap7": {
        "tech_lef":    f"{ORFS_FLOW}/platforms/asap7/lef/asap7_tech_1x_201209.lef",
        "cell_lef":    f"{ORFS_FLOW}/platforms/asap7/lef/asap7sc7p5t_28_R_1x_220121a.lef",
        "liberty": [
            f"{ORFS_FLOW}/platforms/asap7/lib/NLDM/asap7sc7p5t_AO_RVT_TT_nldm_211120.lib.gz",
            f"{ORFS_FLOW}/platforms/asap7/lib/NLDM/asap7sc7p5t_INVBUF_RVT_TT_nldm_220122.lib.gz",
            f"{ORFS_FLOW}/platforms/asap7/lib/NLDM/asap7sc7p5t_OA_RVT_TT_nldm_211120.lib.gz",
            f"{ORFS_FLOW}/platforms/asap7/lib/NLDM/asap7sc7p5t_SEQ_RVT_TT_nldm_220123.lib",
            f"{ORFS_FLOW}/platforms/asap7/lib/NLDM/asap7sc7p5t_SIMPLE_RVT_TT_nldm_211120.lib.gz",
        ],
        "clock_layer": "M4",
        "buf_list":    "BUFx4_ASAP7_75t_R BUFx8_ASAP7_75t_R BUFx16f_ASAP7_75t_R",
        "root_buf":    "BUFx4_ASAP7_75t_R",
        "buf_pattern": "*BUFx*_ASAP7*",
        "inv_pattern": "*INVx*_ASAP7*",
        # liberty in ps → convert WNS/TNS to ns by * 0.001
        "time_mult":   "0.001",
    },
    "nangate45": {
        "tech_lef":    f"{ORFS_FLOW}/platforms/nangate45/lef/NangateOpenCellLibrary.tech.lef",
        "cell_lef":    f"{ORFS_FLOW}/platforms/nangate45/lef/NangateOpenCellLibrary.macro.mod.lef",
        "liberty": [
            f"{ORFS_FLOW}/platforms/nangate45/lib/NangateOpenCellLibrary_typical.lib",
        ],
        "clock_layer": "metal4",
        "buf_list":    "CLKBUF_X1 CLKBUF_X2 CLKBUF_X3",
        "root_buf":    "CLKBUF_X3",
        "buf_pattern": "*CLKBUF*",
        "inv_pattern": "*CLKINV*",
        # liberty in ns → no conversion
        "time_mult":   "1.0",
    },
}


def build_cts_tcl(
    pdk, placed_odb, sdc_path, cts_dir,
    cluster_size, cluster_diam, buf_dist, max_wire,
):
    """Return a complete OpenROAD TCL script for one CTS sweep point."""
    p = PDK_CONTAINER_PATHS[pdk]

    read_lef_cmds = f"read_lef {{{p['tech_lef']}}}\nread_lef {{{p['cell_lef']}}}"
    read_lib_cmds = "\n".join(f"read_liberty {{{lib}}}" for lib in p["liberty"])

    return f"""\
# Auto-generated by 5-run-cts-orfs.py — do not edit
# PDK: {pdk}  cluster_size={cluster_size} cluster_diam={cluster_diam}
# buf_dist={buf_dist} max_wire={max_wire}

# ---- Read LEF ----
{read_lef_cmds}

# ---- Read Liberty ----
{read_lib_cmds}

# ---- Read placed design ----
read_db {{{placed_odb}}}
read_sdc {{{sdc_path}}}

# ---- Clock tree synthesis ----
set_wire_rc -clock -layer {p['clock_layer']}

clock_tree_synthesis \\
    -buf_list       {{{p['buf_list']}}} \\
    -root_buf       {p['root_buf']} \\
    -sink_clustering_enable \\
    -sink_clustering_size          {cluster_size} \\
    -sink_clustering_max_diameter  {cluster_diam} \\
    -distance_between_buffers      {buf_dist}

repair_clock_nets -max_wire_length {max_wire}

# ---- STA ----
set_propagated_clock [all_clocks]
estimate_parasitics -placement
set_power_activity -input_activity 0.1 -activity 0.1

# ---- Collect metrics ----
set tmult {p['time_mult']}

proc safe_call {{cmd}} {{
    if {{[catch {{set v [uplevel 1 $cmd]}} err]}} {{ return "" }}
    return $v
}}

set swns [safe_call {{expr {{[sta::worst_slack        -max] * $tmult}}}}]
set stns [safe_call {{expr {{[sta::total_negative_slack -max] * $tmult}}}}]
set hwns [safe_call {{expr {{[sta::worst_slack        -min] * $tmult}}}}]
set htns [safe_call {{expr {{[sta::total_negative_slack -min] * $tmult}}}}]

# Clock skew (also in PDK time units → convert)
set skew_setup [safe_call {{expr {{[sta::worst_clk_skew -max] * $tmult}}}}]
set skew_hold  [safe_call {{expr {{[sta::worst_clk_skew -min] * $tmult}}}}]

# CTS report → parsed by Python
redirect {{{cts_dir}/cts_stats.rpt}} {{ report_cts }}

# Estimated HPWL (µm)
set wl [safe_call {{rsz::hpwl}}]

# Design area (µm²) — used as proxy for utilization since true util needs floorplan
set da [safe_call {{ord::design_area}}]

# Count clock tree buffer/inverter cells via OpenDB
set buf_pat {{{p['buf_pattern']}}}
set inv_pat {{{p['inv_pattern']}}}
set clk_buf_cnt 0
set clk_inv_cnt 0
catch {{
    set db    [ord::get_db]
    set block [[$db getChip] getBlock]
    foreach inst [$block getInsts] {{
        set mname [[$inst getMaster] getName]
        if {{[string match $buf_pat $mname]}} {{ incr clk_buf_cnt }}
        if {{[string match $inv_pat $mname]}} {{ incr clk_inv_cnt }}
    }}
}}

# ---- Write JSON ----
set fh [open {{{cts_dir}/metrics.json}} w]
puts $fh "\{{"
puts $fh "  \\"setup_wns\\": \\"$swns\\","
puts $fh "  \\"setup_tns\\": \\"$stns\\","
puts $fh "  \\"hold_wns\\":  \\"$hwns\\","
puts $fh "  \\"hold_tns\\":  \\"$htns\\","
puts $fh "  \\"skew_setup\\": \\"$skew_setup\\","
puts $fh "  \\"skew_hold\\":  \\"$skew_hold\\","
puts $fh "  \\"wirelength\\": \\"$wl\\","
puts $fh "  \\"design_area\\": \\"$da\\","
puts $fh "  \\"clock_buffers\\": \\"$clk_buf_cnt\\","
puts $fh "  \\"clock_inverters\\": \\"$clk_inv_cnt\\""
puts $fh "\}}"
close $fh

puts "CTS metrics written to {cts_dir}/metrics.json"
exit
"""


def run_cts_sweep(placement_id, pdk):
    run_dir = os.path.join(CTS_BENCH_ROOT, "runs", placement_id)
    stats_path = os.path.join(CTS_BENCH_ROOT, f"latest_stats_{placement_id}.json")

    with open(stats_path) as f:
        stats = json.load(f)

    placed_odb = stats["placed_odb"]
    sdc_path   = stats["sdc_path"]

    if not os.path.exists(placed_odb):
        sys.exit(f"Placed ODB not found: {placed_odb}")

    base_cts_dir = os.path.join(run_dir, "CTS-experiments")
    os.makedirs(base_cts_dir, exist_ok=True)

    for i in range(10):
        knobs = {
            "CTS_SINK_CLUSTERING_MAX_DIAMETER": random.randint(35, 70),
            "CTS_SINK_CLUSTERING_SIZE":         random.randint(12, 30),
            "CTS_DISTANCE_BETWEEN_BUFFERS":     random.randint(70, 150),
            "CTS_CLK_MAX_WIRE_LENGTH":          random.randint(130, 280),
        }
        print(f"  CTS-{i+1} knobs: {knobs}")

        cts_dir = os.path.join(base_cts_dir, f"CTS-{i+1}")
        os.makedirs(cts_dir, exist_ok=True)

        with open(os.path.join(cts_dir, "knobs.json"), "w") as f:
            json.dump(knobs, f, indent=4)

        tcl_content = build_cts_tcl(
            pdk=pdk,
            placed_odb=placed_odb,
            sdc_path=sdc_path,
            cts_dir=cts_dir,
            cluster_size=knobs["CTS_SINK_CLUSTERING_SIZE"],
            cluster_diam=knobs["CTS_SINK_CLUSTERING_MAX_DIAMETER"],
            buf_dist=knobs["CTS_DISTANCE_BETWEEN_BUFFERS"],
            max_wire=knobs["CTS_CLK_MAX_WIRE_LENGTH"],
        )
        tcl_path = os.path.join(cts_dir, "cts_sweep.tcl")
        with open(tcl_path, "w") as f:
            f.write(tcl_content)

        result = subprocess.run([
            CONTAINER_CMD, "exec",
            "--bind", f"{CTS_BENCH_ROOT}:{CTS_BENCH_ROOT}",
            ORFS_SIF,
            OPENROAD_BIN, "-exit", tcl_path,
        ], cwd=cts_dir)

        if result.returncode != 0:
            print(f"  CTS-{i+1} failed (exit {result.returncode})")
        else:
            metrics_json = os.path.join(cts_dir, "metrics.json")
            if os.path.exists(metrics_json):
                print(f"  CTS-{i+1} complete")
            else:
                print(f"  CTS-{i+1}: openroad exited 0 but metrics.json missing")


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python3 5-run-cts-orfs.py <placement_id> <pdk>")
        sys.exit(1)
    run_cts_sweep(sys.argv[1], sys.argv[2])
